const dayIcons = {
  1000: '/icons/clear_day.svg',
  1001: '/icons/cloudy.svg',
  1100: '/icons/mostly_clear_day.svg',
  1101: '/icons/partly_cloudy_day.svg',
  1102: '/icons/mostly_cloudy.svg',
  2000: '/icons/fog.svg',
  2100: '/icons/fog_light.svg',
  4000: '/icons/drizzle.svg',
  4001: '/icons/rain.svg',
  4200: '/icons/rain_light.svg',
  4201: '/icons/rain_heavy.svg',
  5000: '/icons/snow.svg',
  5001: '/icons/flurries.svg',
  5100: '/icons/snow_light.svg',
  5101: '/icons/snow_heavy.svg',
  6000: '/icons/freezing_drizzle.svg',
  6001: '/icons/freezing_rain.svg',
  6200: '/icons/freezing_rain_light.svg',
  6201: '/icons/freezing_rain_heavy.svg',
  7000: '/icons/ice_pellets.svg',
  7101: '/icons/ice_pellets_heavy.svg',
  7102: '/icons/ice_pellets_light.svg',
  8000: '/icons/tstorm.svg',
  0: '/icons/clear_day.svg',
  1: '/icons/mostly_clear_day.svg',
  2: '/icons/partly_cloudy_day.svg',
  3: '/icons/cloudy.svg',
  45: '/icons/fog.svg',
  48: '/icons/fog_light.svg',
  51: '/icons/drizzle.svg',
  53: '/icons/drizzle.svg',
  55: '/icons/rain_heavy.svg',
  56: '/icons/freezing_drizzle.svg',
  57: '/icons/freezing_rain_heavy.svg',
  61: '/icons/rain_light.svg',
  63: '/icons/rain.svg',
  65: '/icons/rain_heavy.svg',
  66: '/icons/freezing_rain_light.svg',
  67: '/icons/freezing_rain_heavy.svg',
  71: '/icons/snow_light.svg',
  73: '/icons/snow.svg',
  75: '/icons/snow_heavy.svg',
  77: '/icons/ice_pellets.svg',
  80: '/icons/rain_light.svg',
  81: '/icons/rain.svg',
  82: '/icons/rain_heavy.svg',
  85: '/icons/snow_light.svg',
  86: '/icons/snow_heavy.svg',
  95: '/icons/tstorm.svg',
  96: '/icons/tstorm.svg',
  99: '/icons/tstorm.svg'
};


const nightIcons = {
  10001: '/icons/clear_night.svg',
  10011: '/icons/cloudy.svg',
  11001: '/icons/mostly_clear_night.svg',
  11011: '/icons/partly_cloudy_night.svg',
  11021: '/icons/mostly_cloudy.svg',
  20001: '/icons/fog.svg',
  21001: '/icons/fog_light.svg',
  40001: '/icons/drizzle.svg',
  40011: '/icons/rain.svg',
  42001: '/icons/rain_light.svg',
  42011: '/icons/rain_heavy.svg',
  50001: '/icons/snow.svg',
  50011: '/icons/flurries.svg',
  51001: '/icons/snow_light.svg',
  51011: '/icons/snow_heavy.svg',
  60001: '/icons/freezing_drizzle.svg',
  60011: '/icons/freezing_rain.svg',
  62001: '/icons/freezing_rain_light.svg',
  62011: '/icons/freezing_rain_heavy.svg',
  70001: '/icons/ice_pellets.svg',
  71011: '/icons/ice_pellets_heavy.svg',
  71021: '/icons/ice_pellets_light.svg',
  80001: '/icons/tstorm.svg',
  1000: '/icons/clear_night.svg',
  1001: '/icons/mostly_clear_night.svg',
  1100: '/icons/partly_cloudy_night.svg',
  1101: '/icons/cloudy.svg',
  1: '/icons/clear_night.svg',
  11: '/icons/mostly_clear_night.svg',
  21: '/icons/partly_cloudy_night.svg',
  31: '/icons/cloudy.svg',
  451: '/icons/fog.svg',
  481: '/icons/fog_light.svg',
  511: '/icons/drizzle.svg',
  531: '/icons/drizzle.svg',
  551: '/icons/rain_heavy.svg',
  561: '/icons/freezing_drizzle.svg',
  571: '/icons/freezing_rain_heavy.svg',
  611: '/icons/rain_light.svg',
  631: '/icons/rain.svg',
  651: '/icons/rain_heavy.svg',
  661: '/icons/freezing_rain_light.svg',
  671: '/icons/freezing_rain_heavy.svg',
  711: '/icons/snow_light.svg',
  731: '/icons/snow.svg',
  751: '/icons/snow_heavy.svg',
  771: '/icons/ice_pellets.svg',
  801: '/icons/rain_light.svg',
  811: '/icons/rain.svg',
  821: '/icons/rain_heavy.svg',
  851: '/icons/snow_light.svg',
  861: '/icons/snow_heavy.svg',
  951: '/icons/tstorm.svg',
  961: '/icons/tstorm.svg',
  991: '/icons/tstorm.svg'
};


export async function getIcon(weatherCode, isDay) {
  return isDay ? dayIcons[weatherCode] : nightIcons[Number(`${weatherCode}1`)] ;
}